name: media

on:
  workflow_dispatch
  push

jobs:
  step1:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    steps:
      - name: Step 1
        run: 
          echo "step 1"
  step2:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    steps:
      - name: Step 2
        run: 
          echo "step 2"